In [25]:
import cv2
import numpy as np 
import matplotlib.pyplot as plt
import os
import time
import mediapipe as mp

## Keypoints using MP Holistic

In [26]:
mp_holistic = mp.solutions.holistic # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities 

In [27]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # Color conversion BGR to RGB
    image.flags.writeable = False # Image is no longer writeable
    results = model.process(image) # Make prediction
    image.flags.writeable = True # Image is now writeable
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # Color conversion RGB to BGR
    return image, results

#### Drawing landmarks

In [28]:
# def draw_landmarks(image, results):
#     mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACE_CONNECTIONS) # Draw face connections
#     mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS) # Draw pose connections
#     mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw left hand connections
#     mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw right hand connections


In [29]:
# mp_drawing = mp.solutions.drawing_utils
# mp_holistic = mp.solutions.holistic
# drawing_styles = mp.solutions.drawing_styles

# def draw_landmarks(image, results):
#     # Draw face landmarks
#     if results.face_landmarks:
#         mp_drawing.draw_landmarks(
#             image, results.face_landmarks, 
#             mp_holistic.FACEMESH_CONTOURS,
#             landmark_drawing_spec=drawing_styles.get_default_face_mesh_contours_style())

#     # Draw pose landmarks
#     if results.pose_landmarks:
#         mp_drawing.draw_landmarks(
#             image, results.pose_landmarks, 
#             mp_holistic.POSE_CONNECTIONS,
#             landmark_drawing_spec=drawing_styles.get_default_pose_landmarks_style())

#     # Draw left hand landmarks
#     if results.left_hand_landmarks:
#         mp_drawing.draw_landmarks(
#             image, results.left_hand_landmarks, 
#             mp_holistic.HAND_CONNECTIONS,
#             landmark_drawing_spec=drawing_styles.get_default_hand_landmarks_style())

#     # Draw right hand landmarks
#     if results.right_hand_landmarks:
#         mp_drawing.draw_landmarks(
#             image, results.right_hand_landmarks, 
#             mp_holistic.HAND_CONNECTIONS,
#             landmark_drawing_spec=drawing_styles.get_default_hand_landmarks_style())

In [30]:
# def draw_landmarks(image, results):
#     # Specify a general drawing spec for landmarks
#     drawing_spec = mp_drawing.DrawingSpec(thickness=1, circle_radius=1)

#     # Draw face landmarks
#     if results.face_landmarks:
#         mp_drawing.draw_landmarks(
#             image, results.face_landmarks, 
#             mp_holistic.FACEMESH_CONTOURS,
#             landmark_drawing_spec=drawing_spec)

#     # Draw pose landmarks
#     if results.pose_landmarks:
#         mp_drawing.draw_landmarks(
#             image, results.pose_landmarks, 
#             mp_holistic.POSE_CONNECTIONS,
#             landmark_drawing_spec=drawing_spec)

#     # Draw hand landmarks
#     if results.left_hand_landmarks:
#         mp_drawing.draw_landmarks(
#             image, results.left_hand_landmarks, 
#             mp_holistic.HAND_CONNECTIONS,
#             landmark_drawing_spec=drawing_spec)
#     if results.right_hand_landmarks:
#         mp_drawing.draw_landmarks(
#             image, results.right_hand_landmarks, 
#             mp_holistic.HAND_CONNECTIONS,
#             landmark_drawing_spec=drawing_spec)


In [31]:
def draw_landmarks(image, results):
    # Define drawing specifications for landmarks and connections
    landmark_drawing_spec = mp_drawing.DrawingSpec(color=(0, 0, 255), thickness=1, circle_radius=1) # Red for landmarks
    connection_drawing_spec = mp_drawing.DrawingSpec(color=(0, 255, 0), thickness=2) # Green for connections

    # Draw face landmarks
    if results.face_landmarks:
        mp_drawing.draw_landmarks(
            image, results.face_landmarks, 
            mp_holistic.FACEMESH_CONTOURS,
            landmark_drawing_spec=landmark_drawing_spec,
            connection_drawing_spec=connection_drawing_spec)

    # Draw pose landmarks
    if results.pose_landmarks:
        mp_drawing.draw_landmarks(
            image, results.pose_landmarks, 
            mp_holistic.POSE_CONNECTIONS,
            landmark_drawing_spec=landmark_drawing_spec,
            connection_drawing_spec=connection_drawing_spec)

    # Draw hand landmarks
    if results.left_hand_landmarks:
        mp_drawing.draw_landmarks(
            image, results.left_hand_landmarks, 
            mp_holistic.HAND_CONNECTIONS,
            landmark_drawing_spec=landmark_drawing_spec,
            connection_drawing_spec=connection_drawing_spec)
    if results.right_hand_landmarks:
        mp_drawing.draw_landmarks(
            image, results.right_hand_landmarks, 
            mp_holistic.HAND_CONNECTIONS,
            landmark_drawing_spec=landmark_drawing_spec,
            connection_drawing_spec=connection_drawing_spec)


In [32]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_CONTOURS, 
                             mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             ) 
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             )


In [89]:
cap=cv2.VideoCapture(0)
with mp_holistic.Holistic(min_detection_confidence=0.5,min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        ret,frame=cap.read()
        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)

        draw_styled_landmarks(image, results)


        cv2.imshow("OpenCV Feed",image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

## Extract Keypoints

In [34]:
results.pose_landmarks

landmark {
  x: 0.5682725
  y: 0.48306614
  z: -1.2396185
  visibility: 0.99986184
}
landmark {
  x: 0.5858235
  y: 0.39698234
  z: -1.2197855
  visibility: 0.9996848
}
landmark {
  x: 0.5997671
  y: 0.39348066
  z: -1.2195048
  visibility: 0.99963623
}
landmark {
  x: 0.6135162
  y: 0.38985845
  z: -1.2198291
  visibility: 0.99962866
}
landmark {
  x: 0.5365142
  y: 0.40250364
  z: -1.2375693
  visibility: 0.9997472
}
landmark {
  x: 0.5108007
  y: 0.40345994
  z: -1.2371187
  visibility: 0.999731
}
landmark {
  x: 0.48559165
  y: 0.40466627
  z: -1.2371795
  visibility: 0.9997293
}
landmark {
  x: 0.62397254
  y: 0.38733232
  z: -0.8505098
  visibility: 0.99960095
}
landmark {
  x: 0.42322594
  y: 0.40719157
  z: -0.9146063
  visibility: 0.9998284
}
landmark {
  x: 0.58722866
  y: 0.5368784
  z: -1.079684
  visibility: 0.99987364
}
landmark {
  x: 0.5268967
  y: 0.54736406
  z: -1.0970204
  visibility: 0.999928
}
landmark {
  x: 0.73556083
  y: 0.6380141
  z: -0.49641234
  visibility

In [35]:
# pose =[]
# for res in results.pose_landmarks.landmark:
#     test=np.array([res.x,res.y,res.z,res.visibility])
#     pose.append(test)

In [36]:
pose=np.array([[res.x,res.y,res.z,res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)


In [37]:
lh=np.array([[res.x,res.y,res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
lh.shape

(63,)

In [38]:
rh=np.array([[res.x,res.y,res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
rh.shape

(63,)

In [39]:
face=np.array([[res.x,res.y,res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
face.shape

(1404,)

In [40]:
def extract_keypoints(results):
    pose=np.array([[res.x,res.y,res.z,res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)
    lh=np.array([[res.x,res.y,res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh=np.array([[res.x,res.y,res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    face=np.array([[res.x,res.y,res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    return np.concatenate([pose,face,lh,rh])

In [41]:
resutl_test = extract_keypoints(results)

In [42]:
resutl_test

array([ 0.56827247,  0.48306614, -1.23961854, ...,  0.        ,
        0.        ,  0.        ])

In [43]:
np.save('resutl_test.npy',resutl_test)

In [44]:
np.load('resutl_test.npy')

array([ 0.56827247,  0.48306614, -1.23961854, ...,  0.        ,
        0.        ,  0.        ])

## Setup Folders for Collection

In [92]:
DATA_PATH=os.path.join('MP_Data')

actions = np.array(['hello', 'thanks', 'iloveyou'])
no_sequences = 30
sequence_length = 30

In [93]:
for action in actions:
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

## Collect Keypoint Values

In [94]:
cap=cv2.VideoCapture(0)
with mp_holistic.Holistic(min_detection_confidence=0.5,min_tracking_confidence=0.5) as holistic:    
    for action in actions:
        for sequence in range(no_sequences):
            for frame_num in range(sequence_length):
                ret,frame=cap.read()
                # Make detections
                image, results = mediapipe_detection(frame, holistic)
                print(results)

                draw_styled_landmarks(image, results)

                if(frame_num==0):
                    cv2.putText(image,'STARTING COLLECTION',(120,200),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),4,cv2.LINE_AA)
                    cv2.putText(image,'Collecting frames for {} Video Number {}'.format(action,sequence),(15,12),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),1,cv2.LINE_AA)
                    cv2.waitKey(2000)
                else:
                    cv2.putText(image,'Collecting frames for {} Video Number {}'.format(action,sequence),(15,12),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),1,cv2.LINE_AA)

                keypoints=extract_keypoints(results)
                npy_path=os.path.join(DATA_PATH,action,str(sequence),str(frame_num))
                np.save(npy_path,keypoints)


                cv2.imshow("OpenCV Feed",image)

                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

## Preprocessing

In [48]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [50]:
label_map = {label:num for num,label in enumerate(actions)}

In [52]:
label_map

{'hello': 0, 'thanks': 1, 'iloveyou': 2}

In [95]:
sequences,labels=[],[]
for action in actions:
    for sequence in np.array(os.listdir(os.path.join(DATA_PATH,action))).astype(int):
        window=[]
        for frame_num in range(sequence_length):
            res=np.load(os.path.join(DATA_PATH,action,str(sequence),'{}.npy'.format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [96]:
np.array(sequences).shape

(90, 30, 1662)

In [97]:
np.array(labels).shape

(90,)

In [98]:
x=np.array(sequences)
x.shape

(90, 30, 1662)

In [99]:
y= to_categorical(labels).astype(int)


In [106]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=29)

In [107]:
y_test

array([[0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]])

## Training LSTM Neural Network

In [108]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense
from tensorflow.keras.callbacks import TensorBoard

In [109]:
log_dir=os.path.join('Logs')
tb_callback=TensorBoard(log_dir=log_dir)

In [110]:
model = Sequential()
model.add(LSTM(64,input_shape=(30,1662),return_sequences=True, activation='relu'))
model.add(LSTM(128,return_sequences=True, activation='relu'))
model.add(LSTM(64,return_sequences=False, activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(actions.shape[0],activation='softmax'))

In [111]:
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['categorical_accuracy'])

In [129]:
model.fit(x_train,y_train,epochs=200,callbacks=[tb_callback])

Epoch 1/200
3/3 [==============================] - 1s 66ms/step - loss: 6.3284e-08 - categorical_accuracy: 1.0000
Epoch 2/200
3/3 [==============================] - 0s 69ms/step - loss: 6.3284e-08 - categorical_accuracy: 1.0000
Epoch 3/200
3/3 [==============================] - 0s 70ms/step - loss: 6.1812e-08 - categorical_accuracy: 1.0000
Epoch 4/200
3/3 [==============================] - 0s 70ms/step - loss: 6.0340e-08 - categorical_accuracy: 1.0000
Epoch 5/200
3/3 [==============================] - 0s 72ms/step - loss: 5.8869e-08 - categorical_accuracy: 1.0000
Epoch 6/200
3/3 [==============================] - 0s 73ms/step - loss: 5.8869e-08 - categorical_accuracy: 1.0000
Epoch 7/200
3/3 [==============================] - 0s 70ms/step - loss: 5.8869e-08 - categorical_accuracy: 1.0000
Epoch 8/200
3/3 [==============================] - 0s 71ms/step - loss: 5.8869e-08 - categorical_accuracy: 1.0000
Epoch 9/200
3/3 [==============================] - 0s 71ms/step - loss: 5.8869e-08 - cat

In [130]:
from sklearn.metrics import confusion_matrix

# Predict on test data
y_pred = model.predict(x_test)

# Convert predictions to labels
y_pred_labels = np.argmax(y_pred, axis=1)
y_true_labels = np.argmax(y_test, axis=1)

# Create confusion matrix
cm = confusion_matrix(y_true_labels, y_pred_labels)
print(cm)



1/1 [==============================] - 0s 29ms/step
[[4 0 0]
 [0 2 0]
 [2 0 1]]


In [131]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_12 (LSTM)              (None, 30, 64)            442112    
                                                                 
 lstm_13 (LSTM)              (None, 30, 128)           98816     
                                                                 
 lstm_14 (LSTM)              (None, 64)                49408     
                                                                 
 dense_12 (Dense)            (None, 64)                4160      
                                                                 
 dense_13 (Dense)            (None, 32)                2080      
                                                                 
 dense_14 (Dense)            (None, 3)                 99        
                                                                 
Total params: 596675 (2.28 MB)
Trainable params: 59667

## Predictions

In [132]:
res=model.predict(x_test)

1/1 [==============================] - 0s 28ms/step


In [133]:
actions[np.argmax(res[1])]

'iloveyou'

In [134]:
model.save('action.h5')

c:\Users\sanja\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [135]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [140]:
yhat = model.predict(x_test)

1/1 [==============================] - 0s 29ms/step


In [141]:
ytrue = np.argmax(y_test, axis = 1).tolist()
yhat = np.argmax(yhat, axis = 1).tolist()

In [142]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[3, 2],
        [0, 4]],

       [[7, 0],
        [0, 2]],

       [[6, 0],
        [2, 1]]], dtype=int64)

In [143]:
accuracy_score(ytrue, yhat)

0.7777777777777778

In [147]:
sequence=[]
sentence=[]
threshold=0.7

cap=cv2.VideoCapture(0)
with mp_holistic.Holistic(min_detection_confidence=0.5,min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        ret,frame=cap.read()
        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)

        draw_styled_landmarks(image, results)


        keypoints=extract_keypoints(results)    
        sequence.append(keypoints)
        sequence=sequence[-30:]

        if len(sequence)==30:
            res=model.predict(np.expand_dims(sequence,axis=0))[0]
            # print(res)
            print(actions[np.argmax(res)])
            # sentence.append(actions[np.argmax(res)])
        
        if res[np.argmax(res)]>threshold:
            if len(sentence)>0:
                if actions[np.argmax(res)]!=sentence[-1]:
                    sentence.append(actions[np.argmax(res)])
            else:
                sentence.append(actions[np.argmax(res)])
        
        if len(sentence)>5:
            sentence=sentence[-5:]
        
        cv2.rectangle(image,(0,0),(640,40),(245,117,16),-1)
        cv2.putText(image,' '.join(sentence),(3,30),cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2,cv2.LINE_AA)


        cv2.imshow("OpenCV Feed",image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

In [148]:
## Random search

In [149]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

def build_lstm_model(n_units, activation, optimizer):
    model = Sequential()
    model.add(LSTM(n_units, activation=activation, return_sequences=True, input_shape=(30, 1662)))
    model.add(LSTM(n_units, activation=activation))
    model.add(Dense(n_units // 2, activation=activation))
    model.add(Dense(actions.shape[0], activation='softmax'))
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [152]:
from sklearn.model_selection import RandomizedSearchCV
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

# Define the hyperparameters and their ranges
param_dist = {
    'n_units': [50, 100, 150, 200],
    'activation': ['relu', 'tanh'],
    'optimizer': ['adam', 'rmsprop']
}

# Wrap the Keras model
model = KerasClassifier(build_fn=build_lstm_model, epochs=100, batch_size=10, verbose=0)

# Perform random search
random_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, n_iter=10, cv=3, n_jobs=-1)
random_search_result = random_search.fit(x_train, y_train)

# Display the results
print("Best: %f using %s" % (random_search_result.best_score_, random_search_result.best_params_))


ModuleNotFoundError: No module named 'tensorflow.keras.wrappers'